// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "_remotedl1.h"

/////////////////////////////////////////////////////////////////////////////
// C_remoteDL1

IMPLEMENT_DYNCREATE(C_remoteDL1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// C_remoteDL1 properties

/////////////////////////////////////////////////////////////////////////////
// C_remoteDL1 operations

CString C_remoteDL1::GetStatusmessage()
{
	CString result;
	InvokeHelper(0x4003000d, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_remoteDL1::SetStatusmessage(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x4003000d, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_remoteDL1::GetCaster()
{
	CString result;
	InvokeHelper(0x68030010, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_remoteDL1::SetCaster(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030010, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_remoteDL1::GetLogin()
{
	CString result;
	InvokeHelper(0x6803000f, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_remoteDL1::SetLogin(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6803000f, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

VARIANT C_remoteDL1::GetLocalIP()
{
	VARIANT result;
	InvokeHelper(0x6803000e, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

CString C_remoteDL1::GetDsn()
{
	CString result;
	InvokeHelper(0x6803000d, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_remoteDL1::SetDsn(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6803000d, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_remoteDL1::GetCommand()
{
	CString result;
	InvokeHelper(0x6803000c, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_remoteDL1::SetCommand(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6803000c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

void C_remoteDL1::DownLoad()
{
	InvokeHelper(0x60030016, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void C_remoteDL1::Cancel()
{
	InvokeHelper(0x60030017, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
