#if !defined(AFX__REMOTEDL1_H__F5C17987_A7E1_11D2_85D5_00104B2D39AC__INCLUDED_)
#define AFX__REMOTEDL1_H__F5C17987_A7E1_11D2_85D5_00104B2D39AC__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// C_remoteDL1 wrapper class

class C_remoteDL1 : public CWnd
{
protected:
	DECLARE_DYNCREATE(C_remoteDL1)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xf3fb5e20, 0xa837, 0x11d2, { 0x91, 0x37, 0x0, 0x60, 0x8, 0x1a, 0xa7, 0xbc } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	CString GetStatusmessage();
	void SetStatusmessage(LPCTSTR lpszNewValue);
	CString GetCaster();
	void SetCaster(LPCTSTR lpszNewValue);
	CString GetLogin();
	void SetLogin(LPCTSTR lpszNewValue);
	VARIANT GetLocalIP();
	CString GetDsn();
	void SetDsn(LPCTSTR lpszNewValue);
	CString GetCommand();
	void SetCommand(LPCTSTR lpszNewValue);
	void DownLoad();
	void Cancel();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__REMOTEDL1_H__F5C17987_A7E1_11D2_85D5_00104B2D39AC__INCLUDED_)
