//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by csda.rc
//
#define IDB_RESET                       3
#define ID_RESET                        3
#define IDC_BUTTON_SET_ALL              3
#define IDC_BUTTON_SELECT_HILITED       5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_DLG_VALIDN_ERRORS           101
#define ID_OUTPUTWINDOW                 101
#define IDD_PPG_ORDER_GROUP             107
#define XXX_IDD_PPG_ORDER_GROUP_DEPRECATED 107
#define IDR_MAINFRAME                   128
#define IDR_CSDATYPE                    129
#define IDR_MAINFRAME2                  129
#define IDD_SCEN_MGR_DLG                130
#define IDR_SCEN_MGR                    130
#define IDC_ZOOMIN                      130
#define IDD_PPG_CI_CODE_SELECT          131
#define IDR_CASTER_SCEN                 131
#define IDB_CALCBTN                     131
#define IDC_ZOOMOUT                     131
#define IDD_PPG_ORDER_RANGE             132
#define IDC_ZOOMRECT                    132
#define IDD_CASTER_SCEN_AVAIL_DLG       133
#define IDI_OPENFOLDER                  133
#define IDC_PAN_HAND                    133
#define IDD_CASTER_SCEN_STRING_DLG      134
#define IDI_CLOSEDFOLDER                134
#define IDD_PPG_ORDER_SORT              135
#define IDD_PPG_ORDER_SELECT            136
#define IDI_SMILEY_FACE                 136
#define IDD_DLG_MRU_SCEN1               136
#define IDR_CASTER_SCEN_GANTT_CHART_VIEW_CONTEXT_MENU 137
#define IDC_ZOOMRECTDRAG                137
#define IDR_SCEN_MGR_CONTEXT_MENU       138
#define IDB_MRU_DLG                     138
#define IDR_CAST_STRING_EDITOR          139
#define IDD_CREATE_SUPER_SCEN           140
#define IDR_SCEN_MASTER                 140
#define IDD_CAST_STRING_ID              141
#define IDR_SCEN_LIST_MASTER            141
#define IDI_ICON_WASTEBASKET            142
#define IDD_PPG_HEAT_SIZES              144
#define IDD_DIALOG_GANTT_COLORS         145
#define IDI_ICON_QUESTION               146
#define IDD_MESSAGE                     147
#define IDC_CURSOR1                     148
#define IDD_PPG_ORDER_CHEM_RANGE        149
#define IDI_ICON_CALC                   150
#define IDI_ICON_QUESTION_ORDER         151
#define IDD_DLG_MINI_CALC               152
#define IDI_ICON_WASTEBASKET1           152
#define IDD_DIALOG_ORDER_INQUIRY        153
#define IDR_MAINFRAME2_LG               153
#define IDD_CASTER_SCEN_HEAT_DETAILS_DLG 154
#define IDD_SCENARIO_DLGBAR             155
#define IDB_SPLASHWND                   156
#define IDD_DLG_CAST_STRING_EDITOR_TEXT_VIEW 157
#define IDD_DLG_STRING_ORDER_PARMS      158
#define IDD_DLG_STRAND_SUMMARY          159
#define IDB_BITMAP_ORDER_INQUIRY        160
#define IDC_CURSOR2                     161
#define IDD_DLG_LOGIN                   162
#define IDB_CSDA                        163
#define IDD_DLG_EMBEDDED_SCEN_MGR       163
#define IDB_INLAND_ICON                 164
#define IDB_AIP_TAGLINE                 165
#define IDB_INLAND_SMALL                166
#define IDD_DLG_CASTER_SCEN_INFO        167
#define IDB_ORDER_LIST                  168
#define IDB_ORDER_IMAGE_LIST            170
#define IDR_MENU_MISC_COMMANDS          171
#define IDB_INSERT_STOCK_ORDER          172
#define IDD_DLG_REPORT                  172
#define IDB_END_OF_ORDER                173
#define IDB_INSERT_ORDER                174
#define IDD_DLG_MULTIPLE_ORDER_INSERT   175
#define IDB_LONG_OPN_IMAGE_LIST         175
#define IDD_DLG_ORDER_NUM               176
#define XXX_IDD_PPG_ORDER_CHEM_RANGE1   177
#define IDD_DLG_LONG_OPN                178
#define IDC_CURSOR3                     180
#define IDD_DLG_MULTISELECT             180
#define IDD_DLG_TAB_NUM                 181
#define IDD_DLG_LONG_OPN1               182
#define IDD_DLG_SELECT_SPEC             183
#define IDB_LOCKED                      185
#define IDB_LOCKED_HEATS                186
#define IDB_UNLOCKED                    187
#define IDB_UNLOCKED_HEATS              188
#define IDB_SAVE                        189
#define IDD_DLG_SCEN_MASTER_CTRL_VIEW   190
#define IDB_LONG_OPN_IMAGE_LIST1        190
#define IDD_DLG_SCEN_LIST_MASTER        191
#define IDC_CURSOR4                     192
#define IDR_SCEN_LIST_MASTER_POPUP      193
#define IDD_DLG_SELECT_909s             194
#define IDD_DLG_STRING_STATUS           195
#define IDB_UPLOAD                      196
#define IDD_DLG_INITIAL_SCEN_LOADER     197
#define IDR_HM_LOAD_GRAPH               198
#define IDD_DLG_UPLOAD                  199
#define IDB_SEMILOCKED_HEATS            199
#define IDB_LOCKED_HEATS_OFF            200
#define IDD_DLG_HM_LOAD_SCEN_SEQ        201
#define IDB_SEMILOCKED_HEATS_OFF        201
#define IDD_DLG_HM_LOAD_SCEN_MGR        202
#define IDB_UNLOCKED_HEATS_OFF          202
#define IDD_DLG_HM_START_TIME           203
#define IDR_HEATS_LOCKED                205
#define IDD_DLG_HEAT_LOCK               207
#define IDD_DLG_DATETIME                209
#define IDR_HM_LOAD_GRAPH_CONTEXT_MENU  211
#define IDB_SMALL_UP                    212
#define IDB_SMALL_DOWN                  213
#define IDD_DLG_EMAIL                   213
#define IDB_ISPAT_LOGO                  214
#define IDD_DLG_VALIDN_ERRORS_POPUP     215
#define IDD_DLG_STRINGBUILDER           216
#define XXX_IDD_PPG_ORDER_RANGE1        217
#define IDD_DLG_PICK_CASTER             222
#define IDC_GROUPBOX_SNAPS              1000
#define IDC_LIST_SNAPS                  1001
#define IDC_GROUPBOX_SUPERSCENS         1002
#define IDC_GROUPBOX_SCENS              1004
#define IDC_TREE_SCENS                  1005
#define IDC_LIST_SUPERSCENS             1006
#define IDC_EDIT_SELECTED_CODES         1007
#define IDC_COMBO_CASTER_NUM            1007
#define IDC_CHECK_ALL_CODES             1008
#define IDC_COMBO_SCENS                 1008
#define IDC_LIST_CI_CODES               1011
#define IDC_CHECK_USE_SPEC_RANGE        1012
#define IDC_CHECK_USE_ALL_SPECS         1012
#define IDC_EDIT_MIN_SPEC               1013
#define IDC_CHECK_CROSS_APP             1013
#define IDC_EDIT_MAX_SPEC               1014
#define IDC_CHECK_USE_WIDTH_RANGE       1015
#define IDC_EDIT_MIN_WIDTH              1016
#define IDC_EDIT_MAX_WIDTH              1017
#define IDC_CHECK_SWING_TONS            1018
#define IDC_CHECK_SHOW_ALL              1019
#define IDC_CHECK_NEW_ORDERS            1019
#define IDC_GROUP_LIST                  1021
#define IDC_ORDER_LIST                  1023
#define IDC_ORDERS_GROUP_BOX            1026
#define IDC_STRAND1_ORDER_LIST          1027
#define IDC_STRAND2_ORDER_LIST          1028
#define IDC_RB_STANDARD                 1028
#define IDC_LIST_GROUPS                 1030
#define IDC_LIST_ORDERS                 1031
#define IDC_RB_VIEW1                    1032
#define IDC_LIST_VALIDATION_STRINGS     1032
#define IDC_RB_VIEW2                    1033
#define IDC_STRING_LIST                 1033
#define IDC_RB_VIEW3                    1034
#define IDC_CHECK_USE_80HSM_LU_TYPE     1035
#define IDC_EDIT_80HSM_LU_TYPE          1036
#define IDC_CHECK_USE_PRIORITY_CODE     1037
#define IDC_EDIT_CI_PRIORITY            1038
#define IDC_EDIT_MIN_CI_PRIORITY        1038
#define IDC_EDIT_ORDER_PRIORITY         1039
#define IDC_EDIT_MAX_CI_PRIORITY        1039
#define IDC_CHECK_HRWK_CURRENT_BACK     1040
#define IDC_CHECK_HRWK_PLUS_1           1041
#define IDC_CHECK_HRWK_PLUS_2           1042
#define IDC_CHECK_HRWK_PLUS_3           1043
#define IDC_CHECK_HRWK_PLUS_4           1044
#define IDC_CHECK_HRWK_FUTURE           1045
#define IDC_LIST_AVAIL_FIELDS           1046
#define IDC_BUTTON_SELECT_FIELD         1047
#define IDC_BUTTON_SELECT_ALL_FIELDS    1048
#define IDC_BUTTON_DESELECT_FIELD       1049
#define IDC_BUTTON_DESELECT_ALL_FIELDS  1050
#define IDC_LIST_GROUP_FIELDS           1052
#define IDC_LIST_SORT_FIELDS            1053
#define IDC_BUTTON_PROMOTE_FIELD        1054
#define IDC_BUTTON_DEMOTE_FIELD         1055
#define IDC_BUTTON_GROUP_1              1056
#define IDC_BUTTON_GROUP_2              1057
#define ID_SNAPSHOT_UPDATE              1058
#define ID_SCEN_COPY                    1059
#define ID_SCEN_EDIT                    1060
#define ID_SCEN_DELETE                  1061
#define ID_SUPER_SCEN_CREATE            1062
#define ID_SCEN_INFO                    1062
#define ID_SUPER_SCEN_DELETE            1064
#define IDC_LIST_CASTER1                1066
#define IDC_LIST_CASTER2                1067
#define IDC_EDIT_YEAR                   1067
#define IDC_LIST_CASTER3                1068
#define IDC_EDIT_CREATION_DATE          1068
#define IDC_EDIT_START1                 1068
#define IDC_SPIN_YEAR                   1071
#define IDC_EDIT_WEEK                   1072
#define IDC_WASTEBASKET                 1072
#define IDC_SPIN_WEEK                   1073
#define IDC_EDIT_LAST_SAVE_DATE         1073
#define IDC_EDIT_CASTER                 1074
#define IDC_EDIT_CASTER1_HEAT_SIZE      1075
#define IDC_SPIN_CASTER                 1075
#define IDC_EDIT_CASTER1_HEAT_SIZE_AIM  1075
#define IDC_EDIT_NUM                    1076
#define IDC_EDIT_CASTER23_HEAT_SIZE     1076
#define IDC_EDIT_CURRENT_WEEK           1076
#define IDC_EDIT_CASTER23_HEAT_SIZE_AIM 1076
#define IDC_EDIT_CURRENT_YEAR           1077
#define IDC_SPIN_NUM                    1077
#define IDC_EDIT_CASTER1_HEAT_SIZE_MIN  1077
#define IDC_SPIN_NUM_HEATS              1078
#define IDC_EDIT_CASTER23_HEAT_SIZE_MIN 1078
#define IDC_EDIT_PLANNED_START          1078
#define IDC_EDIT_CASTER1_HEAT_SIZE_MAX  1079
#define IDC_QUESTION                    1080
#define IDC_EDIT_CASTER23_HEAT_SIZE_MAX 1080
#define IDC_EDIT_MIN_CARBON             1080
#define ID_EDIT_STRAND1_SUMMARY         1081
#define IDC_SPIN_START1                 1081
#define IDC_EDIT_CASTER4_HEAT_SIZE_AIM  1081
#define ID_EDIT_STRAND2_SUMMARY         1082
#define IDC_EDIT_END1                   1082
#define IDC_COMBO_STRINGS               1082
#define IDC_EDIT_CASTER4_HEAT_SIZE_MIN  1082
#define IDC_SPIN_END1                   1083
#define IDC_EDIT_CASTER4_HEAT_SIZE_MAX  1083
#define IDC_EDIT_START2                 1084
#define IDC_EDIT_CASTER5_HEAT_SIZE_AIM  1084
#define IDC_EDIT1                       1085
#define IDC_SPIN_START2                 1085
#define IDC_EDIT_CASTER5_HEAT_SIZE_MIN  1085
#define IDC_BUTTON_UPDATE_GROUPING      1086
#define IDC_EDIT_MAX_CHEM1              1086
#define IDC_EDIT_NUM_HEATS              1086
#define IDC_EDIT_ELT_MN                 1086
#define IDC_EDIT_CAST_LENGTH            1086
#define IDC_EDIT_CASTER23_HEAT_SIZE_MAX3 1086
#define IDC_EDIT_CASTER5_HEAT_SIZE_MAX  1086
#define IDC_EDIT_MAX_CHEM2              1087
#define IDC_EDIT_ELT_SIGNIF             1087
#define IDC_BUTTON_UPDATE_SORTING       1087
#define IDC_EDIT_END2                   1087
#define IDC_EDIT_CAST_LENGTH2           1087
#define IDC_EDIT_MAX_CHEM3              1088
#define IDC_EDIT_CONDN_CODE             1088
#define IDC_EDIT_ID                     1088
#define IDC_EDIT_HEAT_SIZE_MAX          1088
#define IDC_EDIT_MAX_CHEM4              1089
#define IDC_EDIT_VERSION                1089
#define IDC_EDIT_SPEC                   1089
#define IDC_SPIN_END2                   1089
#define IDC_EDIT_NUM_ORDERS             1089
#define IDC_EDIT_MAX_CHEM5              1090
#define IDC_EDIT_SLIT_TYPE_CODE         1090
#define IDC_EDIT_DISPO_CODE             1090
#define IDC_EDIT_MAX_CARBON             1090
#define IDC_EDIT_MIN_MN                 1091
#define IDC_EDIT_CAST_LENGTH3           1091
#define IDC_EDIT_MAX_MN                 1092
#define IDC_COMBO_SPEC1                 1098
#define IDC_COMBO_SPEC2                 1099
#define IDC_COMBO_CHEM1                 1099
#define IDC_COMBO_SPEC3                 1100
#define IDC_BUTTON_MIN_CHEM1            1100
#define IDC_COMBO_SPEC4                 1101
#define IDC_BUTTON_MAX_CHEM1            1101
#define IDC_COMBO_SPEC5                 1102
#define IDC_EDIT_MIN_CHEM1              1102
#define IDC_COMBO_CHEM2                 1103
#define IDC_BUTTON_CLEAR                1103
#define IDC_EDIT_MIN_CHEM2              1104
#define IDC_BUTTON_CLEAR_ERROR          1104
#define IDC_EDIT_TONS                   1104
#define IDC_BUTTON_MIN_CHEM2            1105
#define IDC_BUTTON_BACKSPACE            1105
#define ID_EDIT_STRAND_SUMMARY          1105
#define IDC_BUTTON_MAX_CHEM2            1106
#define IDC_BUTTON_PERCENT              1106
#define ID_EDIT_STRING_INFO             1106
#define IDC_COMBO_CHEM3                 1107
#define IDC_BUTTON_DIGIT_7              1107
#define IDC_BUTTON_LOOKUP               1107
#define ID_EDIT_HEAT_DETAILS            1107
#define IDC_EDIT_MIN_CHEM3              1108
#define IDC_BUTTON_DIGIT_8              1108
#define IDC_EDIT_ORDER_NUM              1108
#define IDC_BUTTON_MIN_CHEM3            1109
#define IDC_BUTTON_DIGIT_9              1109
#define IDC_EDIT_CUST_NAME              1109
#define IDC_BUTTON_MAX_CHEM3            1110
#define IDC_BUTTON_DIVIDE               1110
#define IDC_EDIT_CUST_CODE              1110
#define IDC_COMBO_CHEM4                 1111
#define IDC_BUTTON_DIGIT_4              1111
#define IDC_EDIT_HR_WEEK                1111
#define IDC_EDIT_HR_WEEK_YEAR           1111
#define IDC_EDIT_MIN_CHEM4              1112
#define IDC_BUTTON_DIGIT_5              1112
#define IDC_EDIT_HR_YEAR                1112
#define IDC_BUTTON_MIN_CHEM4            1113
#define IDC_BUTTON_DIGIT_6              1113
#define IDC_EDIT_COMMODITY_PRIORITY     1113
#define IDC_EDIT_PRIORITY_CODE          1113
#define IDC_BUTTON_MAX_CHEM4            1114
#define IDC_BUTTON_MULTIPLY             1114
#define IDC_EDIT_PLANNED_START_DATE     1114
#define IDC_COMBO_CHEM5                 1115
#define IDC_BUTTON_DIGIT_1              1115
#define IDC_EDIT_UNIT_PREF              1115
#define IDC_EDIT_MIN_CHEM5              1116
#define IDC_BUTTON_DIGIT_2              1116
#define IDC_EDIT_FACL_PREF1             1116
#define IDC_BUTTON_MIN_CHEM5            1117
#define IDC_BUTTON_DIGIT_3              1117
#define IDC_EDIT_FACL_PREF2             1117
#define IDC_BUTTON_MAX_CHEM5            1118
#define IDC_BUTTON_SUBTRACT             1118
#define IDC_EDIT_FACL_PREF3             1118
#define IDC_BUTTON_DIGIT_0              1119
#define IDC_BUTTON_DECIMAL              1120
#define IDC_LIST_HEATS                  1120
#define IDC_BUTTON_ADD                  1121
#define IDC_EDIT_SLAB_WIDTH             1121
#define IDC_STRING_ID                   1121
#define IDC_EDIT_HB_WIDTH               1122
#define IDC_COMBO_SPEC                  1122
#define IDC_EDIT_SLAB_GAUGE             1123
#define IDC_LIST_CHEMS                  1123
#define IDC_EDIT_ORDERED_GAUGE          1123
#define IDC_COMBO_PRESETS               1123
#define IDC_BUTTON_PASTE                1124
#define IDC_EDIT_HB_GAUGE               1124
#define IDC_BUTTON_EQUAL                1125
#define IDC_EDIT_SLAB_LENGTH            1125
#define IDC_EDIT_ELT_C                  1126
#define IDC_EDIT_CB_WIDTH               1126
#define IDC_EDIT_SLAB_WEIGHT            1127
#define IDC_EDIT_NUM_PIECES             1128
#define IDC_EDIT_CI_CODE                1129
#define IDC_EDIT_EXP_CODE               1130
#define IDC_EDIT_SLAB_CONDN_CODE        1131
#define IDC_EDIT_MEGA_LU_CODE           1132
#define IDC_EDIT_ORDERED_SPEC           1133
#define IDC_EDIT_STEEL_SPEC             1134
#define IDC_EDIT_CAST_SPEC              1135
#define IDC_EDIT_ELT_C_MIN              1136
#define IDC_EDIT_MIN_SLAB_WIDTH         1136
#define IDC_LIST_ON_LINEUP              1137
#define IDC_EDIT_HEAT_NUMBER            1137
#define IDC_EDIT_ELT_C_MAX              1138
#define IDC_EDIT_MAX_SLAB_WIDTH         1138
#define IDC_EDIT_ELT_MN_MIN             1139
#define IDC_EDIT_MIN_SLAB_LENGTH        1139
#define IDC_EDIT_ELT_MN_MAX             1140
#define IDC_EDIT_MAX_SLAB_LENGTH        1140
#define IDC_EDIT_ELT_SIGNIF_MIN         1141
#define IDC_BUTTON_PRODN                1141
#define IDC_EDIT_MAX_TRANS_SLAB_WIDTH   1141
#define IDC_EDIT_ELT_SIGNIF_MAX         1142
#define IDC_COMBO_CASTER_1              1142
#define IDC_EDIT_FP_MELT_PST            1142
#define IDC_COMBO_CASTER_2              1144
#define IDC_EDIT_FP_ISHRO_PRIO          1144
#define IDC_COMBO_CASTER_3              1145
#define IDC_EDIT_FP_MTO_FLOW            1145
#define IDC_COMBO_PRODN                 1146
#define IDC_RB_CASTER_1                 1147
#define IDC_RB_CASTER_2                 1148
#define IDC_RB_CASTER_3                 1149
#define IDC_COMBO_STRING                1153
#define IDC_LIST_GROUP_SORT_AVAIL_FIELDS 1156
#define IDC_BUTTON_PRINT                1156
#define IDC_STATIC_OPERATION            1157
#define IDC_STATIC_ORDER_NUM            1158
#define IDC_STATIC_ORDERED_CAST_WIDTH   1159
#define IDC_STATIC_ORDERED_CAST_LENGTH  1160
#define IDC_STATIC_ORDERED_NUM_PIECES   1161
#define IDC_STATIC_ORDERED_CONDN_CODE   1162
#define IDC_EDIT_CAST_WIDTH             1163
#define IDC_LIST_SUMMARY                1164
#define IDC_STATIC_MIN_CAST_WIDTH       1164
#define IDC_EXPLORER1                   1164
#define IDC_CHECK_CMS_FLIPS             1165
#define IDC_STATIC_MIN_CAST_LENGTH      1165
#define IDC_CHECK_SLITS_SPLITS          1166
#define IDC_SPIN_NUM_PIECES             1166
#define IDC_CHECK_AVG_WIDTH             1167
#define IDC_SPIN_CAST_WIDTH             1167
#define IDC_CHECK_CURRENT_BACK_FUTURE   1168
#define IDC_SPIN_CAST_LENGTH            1168
#define IDC_CHECK_STOCK                 1169
#define IDC_USERNAME                    1169
#define IDC_STATIC_MAX_CAST_WIDTH       1169
#define IDC_EDIT_PASSWORD               1170
#define IDC_STATIC_MAX_CAST_LENGTH      1170
#define IDC_CHECK_HEAT_STRANDS          1170
#define IDC_SPIN_DISP_CODE              1171
#define IDC_EDIT_CASTER_NUM             1172
#define IDC_STATIC_MIN_CAST_WIDTH_TRANS 1172
#define IDC_EDIT_OWNER                  1173
#define IDC_STATIC_MAX_CAST_WIDTH_TRANS 1173
#define IDC_EDIT_COMMENT                1174
#define IDC_STATIC_PROV_CAST_WIDTH_MAX  1174
#define IDC_BUTTON_REVERT               1175
#define IDC_BUTTON_SAVE                 1176
#define IDC_EDIT_HEAT_SIZE_MIN          1176
#define IDC_BUTTON_UPDATE_COMMENT       1177
#define IDC_EDIT_HEAT_SIZE_AIM          1177
#define IDC_EDIT_HEAT_SIZE_MIN_LIMIT    1178
#define IDC_EDIT_HEAT_SIZE_MAX_LIMIT    1179
#define IDC_EDIT_INSERT_STOCK_ORDER     1181
#define IDC_LIST_CHEMISTRIES            1182
#define IDC_STRAND1_END                 1183
#define IDC_STRAND2_END                 1184
#define IDC_ORDER_TO_INSERT             1189
#define IDC_GRID1                       1190
#define IDC_BUTTON_SPLIT                1192
#define IDC_BUTTON_DELETE               1193
#define IDC_BUTTON_NEW                  1194
#define IDC_BUTTON_LOAD                 1194
#define IDC_BUTTON_UP                   1195
#define IDC_BUTTON_REFRESH              1195
#define IDC_BUTTON_DOWN                 1196
#define IDC_BUTTON_JOIN                 1197
#define IDC_BUTTON_RESET_ALL            1197
#define IDC_BUTTON_NEW_STOCK            1198
#define IDC_BUTTON_RESET_CARBON         1198
#define IDC_BUTTON_RESET_MANGANESE      1199
#define IDC_BUTTON_ORDER_INQUIRY        1199
#define IDC_BUTTON_RESET_3              1200
#define IDC_BUTTON_RESET_4              1201
#define IDC_BUTTON_RESET_5              1202
#define IDC_LIST_PRESET_RANGES          1203
#define IDC_LIST1                       1204
#define IDC_RADIO_SHOW_THIS_CASTER      1205
#define IDC_LIST_SELECTED_SCENS         1205
#define IDC_LIST_CC                     1205
#define IDC_RADIO_SHOW_SWING_TONS       1206
#define IDC_RADIO_SHOW_ALL              1207
#define IDC_GRID_HEAT_DETAILS           1208
#define IDC_BUTTON_SET_CHEMS            1209
#define IDC_TAB1                        1210
#define IDC_BUTTON_SET_SPECS            1211
#define IDC_RADIO_FIRST_DIGIT_1         1211
#define IDC_BUTTON_SET_TAB_NUMS         1212
#define IDC_RADIO_FIRST_DIGIT_2         1212
#define IDC_BUTTON_VALIDATE             1213
#define IDC_RADIO_FIRST_DIGIT_3         1213
#define IDC_BUTTON_UPLOAD               1214
#define IDC_RADIO_FIRST_DIGIT_9         1214
#define IDC_EDIT_TAB_NUM                1215
#define IDC_BUTTON_MARK_ALL             1215
#define IDC_BUTTON_CLEAR_MARKS          1216
#define IDC_GRID_HEAT_CHEMS             1217
#define IDC_LIST_ORDERED_SPECS          1219
#define IDC_COMBO_SLIT_TYPE_CODE        1220
#define IDC_LIST_CROSSAPP_SPECS         1220
#define IDC_COMBO_VALIDATION_ERROR      1221
#define IDC_COMBO_STOCK_COMMERCIAL_REASON 1221
#define IDC_COMBO_STOCK_REASON          1222
#define IDC_EDIT_CHANGE_INDICATOR       1223
#define IDC_BUTTON_CLEAR_CHANGE_INDICATOR 1224
#define IDC_BUTTON_EDIT_ORDERS1         1225
#define IDC_EDIT_EXPOSURE_CODE          1225
#define IDC_BUTTON_EDIT_ORDERS2         1226
#define IDC_BUTTON_SELECT_ONE           1228
#define IDC_BUTTON_SELECT_ALL           1229
#define IDC_BUTTON_DESELECT_ONE         1230
#define IDC_BUTTON_DESELECT_ALL         1231
#define IDC_LIST_AVAILABLE_SCENS        1232
#define IDC_STATIC_CAPTION              1233
#define IDC_LIST_1SC_910s               1234
#define IDC_LIST_1SC_909s               1235
#define IDC_LIST_1SC_SEL_SCEN           1236
#define IDC_COMBO_1SC_SCENS             1237
#define IDC_BUTTON_1SC_PROMOTE          1239
#define IDC_BUTTON_1SC_SCEN_OPS         1240
#define IDC_LIST_909s                   1242
#define IDC_LIST_2SC_910s               1243
#define IDC_LIST_2SC_909s               1244
#define IDC_LIST_2SC_SEL_SCEN           1245
#define IDC_LIST_910s                   1245
#define IDC_COMBO_2SC_SCENS             1246
#define IDC_GRID_STRING_STATUS          1246
#define IDC_BUTTON_HEAT_DETAILS         1247
#define IDC_LIST_CASTER_1               1248
#define IDC_BUTTON_2SC_PROMOTE          1249
#define IDC_LIST_CASTER_2               1249
#define IDC_BUTTON_2SC_SCEN_OPS         1250
#define IDC_LIST_CASTER_3               1250
#define IDC_BUTTON_3CC_PROMOTE          1251
#define IDC_RB_MOST_RECENT_SCEN         1251
#define IDC_LIST_3CC_910s               1252
#define IDC_RB_MOST_RECENT_DAY          1252
#define IDC_STATIC_STRAND1_GROUP        1252
#define IDC_LIST_3CC_909s               1253
#define IDC_RB_ALL                      1253
#define IDC_STATIC_STRAND2_GROUP        1253
#define IDC_LIST_3CC_SEL_SCEN           1254
#define IDC_STATIC_GROUP_GROUP          1254
#define IDC_COMBO_3CC_SCENS             1255
#define IDC_STATIC_AVAIL_GROUP          1255
#define IDC_BUTTON_3CC_SCEN_OPS         1256
#define IDC_REMOTEDL1                   1256
#define IDC_LIST_STRING_SEQ             1257
#define IDC_BUTTON_UPDATE_STRING_SEQ    1258
#define IDC_BUTTON_RESET_STRING_SEQ     1259
#define IDC_STATIC_STRING_ID            1261
#define IDC_EDIT_START_TIME             1262
#define IDC_GROUPBOX_ALL                1263
#define IDC_EDIT_FINISH_TIME            1263
#define IDC_EDIT_TURNAROUND_TIME        1263
#define IDC_BUTTON_NONE                 1266
#define IDC_BUTTON_SOME                 1267
#define IDC_BUTTON_ALL                  1268
#define IDC_EDIT_NUMBER                 1270
#define IDC_SPIN1                       1271
#define IDC_CHECK_USE_TRANS_WIDTHS      1274
#define IDC_EDIT_DATETIME               1277
#define IDC_LIST_TO                     1284
#define IDC_EDIT_SUBJECT                1285
#define IDC_EDIT_BODY                   1286
#define ID_VALIDATE                     1287
#define IDC_LIST_RESULTS                1288
#define IDC_LIST_VALIDN                 1289
#define IDC_LIST_STRINGS                1290
#define IDC_BUTTON_ID                   1292
#define IDC_BUTTON_SELECT               1293
#define IDC_BUTTON_START_SB             1294
#define IDC_BUTTON_CREATE_STRING        1295
#define IDC_SBDRIVER1                   1300
#define IDC_MSG                         1301
#define IDC_CHECK_PST_LT_8              1302
#define IDC_CHECK_PST_8_14              1303
#define IDC_RADIO1                      1303
#define IDC_CHECK_PST_15_21             1304
#define IDC_RADIO2                      1304
#define IDC_CHECK_PST_22_28             1305
#define IDC_RADIO3                      1305
#define IDC_CHECK_PST_29_35             1306
#define IDC_STATIC_LABEL                1306
#define IDC_CHECK_PST_GT_35             1307
#define IDC_CHECK_PRIORITY              1308
#define IDC_STATIC_PRIO_TONS            1309
#define IDC_STATIC_PST_LT_8_TONS        1310
#define IDC_STATIC_PST_8_14_TONS        1311
#define IDC_STATIC_PST_15_21_TONS       1312
#define IDC_STATIC_PST_22_28_TONS       1313
#define IDC_STATIC_PST_29_35_TONS       1314
#define IDC_STATIC_PST_GT_35_TONS       1315
#define IDC_BUTTON_UPDATE_TONS          1316
#define IDC_COMBO_MATCHING_ORDERS       1317
#define IDC_EDIT_NUM_SEGMENTS           1318
#define IDC_EDIT_TONS_DUE_ONLU          1319
#define IDC_STATIC_PROV_CAST_WIDTH_MIN  1319
#define IDC_EDIT_PIECES_DUE_ONLU        1320
#define IDC_STATIC_HOTROLL_UNIT_NAME    1320
#define IDC_EDIT_PARENT_TONS_DUE_ONLU   1321
#define IDC_COMBO1                      1321
#define IDC_EDIT_PARENT_PIECES_DUE_ONLU 1322
#define IDC_COMBO2                      1322
#define ID_EDIT_EDITCASTERSCEN          32771
#define ID_VIEW_AVAILABLEORDERS         32772
#define ID_ZOOM_IN                      32773
#define ID_ZOOM_OUT                     32774
#define ID_SHOW_ALL                     32775
#define ID_EDIT_BM_TOGGLE               32775
#define ID_SUPER_SCEN_VIEW              32781
#define ID_EDIT_BM_NEXT                 32783
#define ID_SCEN_CREATE                  32784
#define ID_EDIT_CREATE_STRING           32785
#define ID_EDIT_DELETE_STRING           32786
#define ID_VIEW_SCENARIO_MANAGER        32787
#define ID_VIEW_MISCCONSTANTS           32788
#define ID_VIEW_MISC_CONSTANTS          32789
#define ID_EDIT_BM_PREV                 32789
#define ID_VIEW_GANTT_COLOR_CHART       32790
#define ID_EDIT_BM_CLEARALL             32791
#define ID_EDIT_ORDER_INQUIRY           32792
#define ID_DEBUG_STEPINTO               32792
#define ID_BUTTON32793                  32793
#define IDC_BUTTON_EDITABLE             32793
#define ID_DEBUG_STEPOVER               32793
#define ID_BUTTON32794                  32794
#define IDC_BUTTON_HEATS_LOCKED         32794
#define ID_DEBUG_STEPOUT                32794
#define ID_BUTTON32795                  32795
#define ID_DEBUG_RUNTO                  32795
#define ID_VIEW_WORKBOOK                32796
#define ID_FILE_SAVEALL                 32796
#define ID_DEBUG_STOP                   32797
#define ID_ZOOM_PERCENT                 32798
#define ID_EDIT_DELETE                  32798
#define ID_ZOOM_POINTIN                 32801
#define ID_ZOOM_POINTOUT                32802
#define ID_ZOOM_RECTIN                  32803
#define ID_1SC_EDIT_SCEN                32804
#define ID_1SC_COPY_SCEN                32805
#define ID_1SC_CREATE_SCEN              32806
#define ID_1SC_DELETE_SCEN              32807
#define ID_2SC_EDIT_SCEN                32809
#define ID_2SC_COPY_SCEN                32810
#define ID_2SC_CREATE_SCEN              32811
#define ID_3CC_DELETE_SCEN              32812
#define ID_3CC_EDIT_SCEN                32813
#define ID_3CC_COPY_SCEN                32814
#define ID_3CC_CREATE_SCEN              32815
#define ID_2SC_DELETE_SCEN              32816
#define ID_MENUITEM32817                32817
#define ID_2SC_DELETE_SCEN2             32817
#define ID_3CC_EDIT_STRING              32818
#define ID_3CC_DELETE_STRING            32819
#define ID_3CC_CREATE_STRING            32820
#define ID_1SC_EDIT_STRING              32821
#define ID_1SC_CREATE_STRING            32822
#define ID_1SC_DELETE_STRING            32823
#define ID_2SC_EDIT_STRING              32824
#define ID_2SC_CREATE_STRING            32825
#define ID_2SC_DELETE_STRING            32826
#define ID_EDIT_FIND_INFILES            32826
#define ID_HEATS_UNLOCKED               32827
#define ID_HEATS_LOCK_1                 32828
#define ID_HEATS_LOCK_2                 32829
#define ID_VIEW_OUTPUT_WINDOW           32829
#define ID_HEATS_LOCK_3                 32830
#define ID_HEATS_LOCK_4                 32831
#define ID_HEATS_LOCK_5                 32832
#define ID_HEATS_LOCK_6                 32833
#define ID_HEATS_LOCK_7                 32834
#define ID_HEATS_LOCK_8                 32835
#define ID_HEATS_LOCK_9                 32836
#define ID_HEATS_LOCK_10                32837
#define ID_HEATS_LOCK_11                32838
#define ID_HEATS_LOCK_12                32839
#define ID_HEATS_LOCK_ALL               32840
#define ID_HEATS_LOCK_PLUS_1            32841
#define ID_VIEW_DAY_PLUS                32842
#define ID_VIEW_DAY_MINUS               32843
#define ID_VIEW_WEEK_PLUS               32844
#define ID_VIEW_WEEK_MINUS              32845
#define ID_VIEW_ADD_ROW                 32846
#define ID_VIEW_DEL_ROW                 32847
#define ID_VIEW_ADD_COL                 32848
#define ID_VIEW_DEL_COL                 32849
#define ID_VIEW_SET_DATE                32850
#define ID_EDIT_MOVE_TO_HOLD_AREA       32851
#define ID_VIEW_SHOW910S                32852
#define ID_VIEW_SCROLLHOLDUP            32853
#define ID_VIEW_SCROLLHOLDDOWN          32854
#define ID_VIEW_SCENARIOS               32855
#define ID_EDIT_LOADHM                  32856
#define ID_EDIT_SENDHM                  32857
#define ID_EDIT_STRINGBUILDER           32858
#define ID_EDIT_PSTCONFORMANCEREPORT    32859
#define ID_EDIT_MOVESTRINGTOOTHERCASTER 32860
#define ID_VIEW_VIEW_OUTPUT_WINDOW      32861
#define ID_EDIT_PLANWORKSHEET           32862
#define ID_FILE_MY_SAVE                 -32646
#define ID_CLEAR_WINDOW                 57610

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        224
#define _APS_NEXT_COMMAND_VALUE         32863
#define _APS_NEXT_CONTROL_VALUE         1323
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
