#if !defined(AFX_SBDRIVER_H__D9054B03_813E_11D3_85F9_00104B2D39AC__INCLUDED_)
#define AFX_SBDRIVER_H__D9054B03_813E_11D3_85F9_00104B2D39AC__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSBDriver wrapper class

class CSBDriver : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSBDriver)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x1b401444, 0x6a64, 0x11d3, { 0xaa, 0x72, 0x0, 0x10, 0x5a, 0xe2, 0x54, 0x35 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	CString GetDNSdata();
	void SetDNSdata(LPCTSTR lpszNewValue);
	CString GetDNSrules();
	void SetDNSrules(LPCTSTR lpszNewValue);
	CString GetDsnforBOFSpeedCalc();
	void SetDsnforBOFSpeedCalc(LPCTSTR lpszNewValue);
	CString GetOrderSource();
	void SetOrderSource(LPCTSTR lpszNewValue);
	CString GetOutputTable();
	void SetOutputTable(LPCTSTR lpszNewValue);
	CString GetPlanCasterUnit();
	void SetPlanCasterUnit(LPCTSTR lpszNewValue);
	CString GetPlanningWeek();
	void SetPlanningWeek(LPCTSTR lpszNewValue);
	CString GetStringID();
	void SetStringID(LPCTSTR lpszNewValue);
	CString GetStartingSpec();
	void SetStartingSpec(LPCTSTR lpszNewValue);
	CString GetDateformat();
	void SetDateformat(LPCTSTR lpszNewValue);
	float GetAimHeatWeight();
	void SetAimHeatWeight(float newValue);
	short GetMaxNumberOfTries();
	void SetMaxNumberOfTries(short nNewValue);
	void MakeString();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SBDRIVER_H__D9054B03_813E_11D3_85F9_00104B2D39AC__INCLUDED_)
